const variable = {
  APPWRITE_PROJECT: process.env.EXPO_PUBLIC_APPWRITE_PROJECT!,
  APPWRITE_ENDPOINT: process.env.EXPO_PUBLIC_APPWRITE_ENDPOINT!,
  APPWRITE_PLATFORM: process.env.EXPO_PUBLIC_APPWRITE_PLATFORM!,

  DATABASE_PRIMARY: process.env.EXPO_PUBLIC_DATABASE_PRIMARY!,
  COLLECTION_USER_CREDENTIALS:
    process.env.EXPO_PUBLIC_COLLECTION_USER_CREDENTIALS!,
  COLLECTION_USER: process.env.EXPO_PUBLIC_COLLECTION_USER!,
  COLLECTION_STUDENT_INFO: process.env.EXPO_PUBLIC_COLLECTION_STUDENT_INFO!,
  COLLECTION_ADMIN_INFO: process.env.EXPO_PUBLIC_COLLECTION_ADMIN_INFO!,
  COLLECTION_SECURITY_INFO: process.env.EXPO_PUBLIC_COLLECTION_SECURITY_INFO!,
  COLLECTION_LOG: process.env.EXPO_PUBLIC_COLLECTION_LOG!,
  COLLECTION_GUARDIAN: process.env.EXPO_PUBLIC_COLLECTION_GUARDIAN!,
  FUNCTION_ACCOUNT: process.env.EXPO_PUBLIC_FUNCTION_ACCOUNT!,
  FUNCTION_INOUT: process.env.EXPO_PUBLIC_FUNCTION_INOUT!,
  BUCKET_IMAGE: process.env.EXPO_PUBLIC_BUCKET_IMAGE!,
};

export const env = variable;
